Recover from partial DICOM transfers from archives to Orthanc Raw (#497)
* Add fixtures for the messages used in testing the imaging api

* Only keep the most recent study in orthanc raw

* refactor _process_message to only pull missing instances if a study already exists in orthanc raw

* Add test for partial dicom transfer

* Test dicom have correct tags in orthanc raw

* Don't autoroute from orthanc raw to orthanc anon

* Try updating the tests

* Try updating the tests

* Try updating the tests

I should really run this locally but YOLO

* Try updating the tests

I should really run this locally but YOLO

* Update partial dicom with production changes (#500)

* Keep gating for routing to anon

* Reduce logging level for finding instances

* Turns out PACS doesn't have image availability tag

* Hardcode some message timeout changes

* Restart orthanc on failure

* Show study UID for debugging

* Don't query by UID if its not set

* Update logging and error messages

* Update processing tests

* Add DICOM titles to imaging-api

* Remove instance availability fully

* Use PIXL dicom timeout when getting answers

* Remove EMAP

* Make timeout an int

Required for getting query answers

* Actually remove emap fully

* Reduce hardcoded timeouts for dicom

* Remove extra stable seconds for orthanc raw

* Remove extra stable seconds for orthanc raw

* Query local using UID, falling back to mrn and accession number

* Lower timeouts

* Save pixl tag to database for faster querying

* Use query timeout for get requests

* Try C-MOVE for all instance UIDs in single query

* Fix types for missing instances

* Fix generator expression

* Specify required UIDs in missing instances query

* Update pixl_imaging/src/pixl_imaging/_orthanc.py

Co-authored-by: Paul Smith <paul.j.smith@ucl.ac.uk>

* Rename send to anon function

* Update orthanc/orthanc-raw/config/dicom.json

---------

Co-authored-by: Paul Smith <paul.j.smith@ucl.ac.uk>

* Add Orthanc.http_timeout and Orthanc.dicom_timeout attributes

* Set 'Synchronour' to False for send_study_to_anon

* Set http_timeout and dicom_timeout arguments for WriteableOrtahnc in testing

* Add PIXL_QUERY_TIMEOUT env var to imaging tests

* Use correct timeouts in calls to orthanc api

* Don't delete a study if modifying the tag fails

* Add OnChange callback to pixl raw plugin to send to anon

Don't send if study is not stable or if project name is not set
Also set http timeout in all posts to orthanc

* Use 5 threads for modifying resources in orthanc raw

* Add debug statements when deleteing and querying local data in orthanc

* Only use study_uid to query local resources if study_uid is not an empty string

* Explicitly trigger c-store from raw to anon, and do so asynchronously

* Move check of ORTHANC_AUTOROUTE_RAW_TO_ANON from orthanc raw plugin to imaging api

Otherwise imaging api tests fail with

 aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://localhost:8044/jobs/None')

* Increase PIXL_DICOM_TRANSFER_TIMEOUT to 60 seconds for system tests

* Always restart the orthanc-raw container

* Set StorageCommitment to True for the c-store operation from raw to anon

* Move triggering c-store operation out of orthanc raw plugin and into pixl_imaging._processing

---------

Co-authored-by: Stef Piatek <s.piatek@ucl.ac.uk>